<?php
echo "<html>";
echo "<body>";
echo "<style>h1 {
    text-align: center;
    margin-top: 20px;
    margin-bottom: 10px;
    font-size: 26px;
  }
  h2 {
    margin-top: 2px;
    margin-bottom: 2px;
    font-size: 22px;
    border-radius: 10px;
  }</style>";
echo "<h1>Data Pendaftar PPDB Jalur Zonasi Tahun 2021</h1>";
echo "<h2>Info Pendaftaran</h2>";
echo "NISN = ";
print_r($_POST['nisn']);
echo "<br>";
echo "Asal Sekolah = ";
print_r($_POST['asalsekolah']);
echo "<br>";
echo "Tahun Lulus = ";
print_r($_POST['tahunlulus']);
echo "<br>";
echo "Lampiran Ijazah = ";
print_r($_POST['lampiranijazah']);
echo "<br>";
echo "<h2>Data Calon Peserta</h2>";
echo "Nama Lengkap = ";
print_r($_POST['namalengkap']);
echo "<br>";
echo "NIK = ";
print_r($_POST['nik']);
echo "<br>";
echo "Tempat Lahir = ";
print_r($_POST['tempatlahir']);
echo "<br>";
echo "Tanggal Lahir = ";
print_r($_POST['tanggallahir']);
echo "<br>";
echo "Lampiran Akte = ";
print_r($_POST['lampiranakte']);
echo "<br>";
echo "Jenis Kelamin = ";
print_r($_POST['jeniskelamin']);
echo "<br>";
echo "Alamat Peserta = ";
print_r($_POST['alamatpeserta']);
echo "<br>";
echo "Desa Peserta = ";
print_r($_POST['desapeserta']);
echo "<br>";
echo "Kecamatan Peserta = ";
print_r($_POST['kecpeserta']);
echo "<br>";
echo "Kabupaten Peserta = ";
print_r($_POST['kabpeserta']);
echo "<br>";
echo "Provinsi Peserta = ";
print_r($_POST['provpeserta']);
echo "<br>";
echo "Email = ";
print_r($_POST['email']);
echo "<h2>Data Orang Tua</h2>";
echo "<br>";
echo "NIK = ";
print_r($_POST['nik']);
echo "<br>";
echo "Lampiran Kartu Keluarga = ";
print_r($_POST['lampirankk']);
echo "<br>";
echo "Nama Ayah = ";
print_r($_POST['namaayah']);
echo "<br>";
echo "Agama Ayah = ";
print_r($_POST['agamaayah']);
echo "<br>";
echo "Pekerjaan Ayah = ";
print_r($_POST['pekerjaanayah']);
echo "<br>";
echo "Nama Ibu = ";
print_r($_POST['namaibu']);
echo "<br>";
echo "Agama Ibu = ";
print_r($_POST['agamaibu']);
echo "<br>";
echo "Pekerjaan Ibu = ";
print_r($_POST['pekerjaanibu']);
echo "<br>";
echo "Alamat Orang Tua = ";
print_r($_POST['alamatorangtua']);
echo "<br>";
echo "Desa Orang Tua = ";
print_r($_POST['desaorangtua']);
echo "<br>";
echo "Kecamatan Orang Tua = ";
print_r($_POST['kecorangtua']);
echo "<br>";
echo "Kabupaten Orang Tua = ";
print_r($_POST['kaborangtua']);
echo "<br>";
echo "Provinsi Orang Tua = ";
print_r($_POST['provorangtua']);

echo "</body>";
echo "</html>";
?>